import React, { useEffect } from 'react';

const TermsOfService: React.FC = () => {
  // Automatically scroll to top when page loads
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <main className="px-6 lg:px-10 pt-32 pb-24 max-w-4xl mx-auto min-h-[70vh]">
      <div className="mb-12">
        <span className="font-lato text-[10px] uppercase tracking-[0.4em] text-[#728156] font-black mb-4 block">Legal</span>
        <h1 className="font-glyseric text-5xl md:text-7xl text-[#2A311F] tracking-tighter leading-none mb-6">
          Terms of <span className="italic font-light text-[#88976c]">Service.</span>
        </h1>
        <p className="font-lato text-sm text-[#728156] font-medium">Last Updated: {new Date().toLocaleDateString()}</p>
      </div>

      <div className="space-y-8 font-lato text-base text-[#2A311F] leading-relaxed">
        <section>
          <h2 className="text-xl font-bold mb-3 text-[#728156]">1. Agreement to Terms</h2>
          <p>By accessing our website and utilizing our digital engineering services, you agree to be bound by these terms of service and all applicable laws and regulations.</p>
        </section>
        
        {/* Add the rest of your actual terms text here */}
        <section>
          <h2 className="text-xl font-bold mb-3 text-[#728156]">2. Intellectual Property</h2>
          <p>The digital artifacts, source code, and design systems generated by Clickora remain the intellectual property of Clickora until full payment and project handover is completed as per the individual service contract.</p>
        </section>
      </div>
    </main>
  );
};

export default TermsOfService;